### ISSUE TITLE
BB Plugin vs BB API

### ISSUE THREAD

**Issue by wildmaster84** [SanderGielisse/BannerBoard-free#3]
What is the idfference between BB plugin and BB api, i know BB api is an api like it says but what exactly does it do?

**Comment by OpticFusion1** [comment]
BB plugin is the main plugin & uses the API.
The API is separate just so it's easier to use, ig?

**Comment by wildmaster84** [comment]
from what i have delt with, i found that the method to create and add the custom maps is what's badly broken. i manageg to only fin a fix for the getHandle but beyond that i have hit a wall.

[CODE]getHandle = Bukkit.getWorld("world").getClass().getMethod("getHandle");[/CODE]
I would imagen that theres a better way to do this so please do let me know!
